# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: README CI

on:
  push:
    branches:
      - 'local-test'
    paths:
      - 'examples/**'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} and generate README file
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn readme
    
    - name: Commit files # copy the new generated README
      run: |
        git config --local user.name "generate-readme"
        git pull
        git add .
        git commit -m "Generate README"
        git push
